New upstream version 3.38

diff --git a/t/zbd/test-zbd-support b/t/zbd/test-zbd-support
--- a/t/zbd/test-zbd-support
+++ b/t/zbd/test-zbd-support
@@ -852,12 +852,15 @@ test31() {
     # To distribute the write target zones evenly, skip certain zones for every
     # write. Utilize zonemode strided for such write patterns.
     bs=$((128 * 1024))
+    off=$((first_sequential_zone_sector * 512))
+    size=$((disk_size - off))
     nz=$((max_open_zones))
     if [[ $nz -eq 0 ]]; then
 	nz=128
     fi
-    off=$((first_sequential_zone_sector * 512))
-    size=$((disk_size - off))
+    if ((size / zone_size < nz)); then
+	nz=$((size / zone_size))
+    fi
     inc=$(((size / nz / zone_size) * zone_size))
     opts=("--name=$dev" "--filename=$dev" "--rw=write" "--bs=${bs}")
     opts+=("--offset=$off" "--size=$((inc * nz))" "--io_size=$((bs * nz))")
@@ -1591,6 +1594,18 @@ test68() {
 		       >> "${logfile}.${test_number}" 2>&1 || return $?
 	# "WRITE:" shall be recoreded only once for the preparation
 	[[ $(grep -c "WRITE:" "${logfile}.${test_number}") == 1 ]]
+}
+
+# Test rw=rw and verify_backlog=1 options do not cause verify failure
+test69() {
+	require_zbd || return "$SKIP_TESTCASE"
+
+	prep_write
+	run_fio --name=job --filename="$dev" --time_based --runtime=15s \
+		--rw=rw --offset=$((first_sequential_zone_sector * 512)) \
+		"$(ioengine "libaio")" --iodepth=32 --randrepeat=0 \
+		--verify=crc32 --verify_backlog=1 --zonemode=zbd --direct=1 \
+		>> "${logfile}.${test_number}" 2>&1 || return $?
 }
 
 SECONDS=0
